// Code written by Kone & Claude | The code does the following: " The Documentation engine (Tiers 1-4).
// 'doc:view' reads and searches the documentation centre; 'doc:manage' can write a document, IMPORT an
// external file (text/markdown/code/PDF) or AI-GENERATE a spec/post-mortem/guide/schema from the live
// system state plus optional source material. Everything is stored and indexed for agent recall. "

import { useEffect, useRef, useState } from 'react';
import { api } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { can } from '../config/roles';
import { RichContent } from '../components/RichContent';
import { type Project, fmtDate, Spinner, Empty } from './dashboards/shared';

interface Doc { id: string; title: string; type: string; status: string; content: string; updatedAt: string; project?: { name: string } | null }
type Mode = 'write' | 'import' | 'generate';
const GEN_KINDS = ['Technical Specification', 'System Post-mortem', 'User Guide', 'API Schema'];

export function DocumentationPage() {
  const { user } = useAuth();
  const manage = can(user, 'doc:manage');
  const [docs, setDocs] = useState<Doc[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [q, setQ] = useState('');
  const [loading, setLoading] = useState(true);
  const [openId, setOpenId] = useState<string | null>(null);
  const [mode, setMode] = useState<Mode>('generate');
  const [busy, setBusy] = useState(false);
  const [toast, setToast] = useState('');
  const [error, setError] = useState('');

  // form state shared across modes
  const [title, setTitle] = useState('');
  const [projectId, setProjectId] = useState('');
  const [docType, setDocType] = useState('Project Brief');
  const [content, setContent] = useState('');
  const [kind, setKind] = useState(GEN_KINDS[0]);
  const [sourceText, setSourceText] = useState('');
  const [upload, setUpload] = useState<{ filename: string; mimeType: string; contentBase64: string } | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  function load(first = false) {
    if (first) setLoading(true);
    api<Doc[]>('/api/documents').then(setDocs).catch((e) => setError(e.message)).finally(() => setLoading(false));
    api<Project[]>('/api/projects').then(setProjects).catch(() => undefined);
  }
  useEffect(() => load(true), []);

  function flash(msg: string) { setToast(msg); setTimeout(() => setToast(''), 3500); }
  function resetForm() { setTitle(''); setContent(''); setSourceText(''); setUpload(null); if (fileRef.current) fileRef.current.value = ''; }

  function onFile(e: React.ChangeEvent<HTMLInputElement>) {
    const f = e.target.files?.[0];
    if (!f) return;
    const reader = new FileReader();
    reader.onload = () => { const b64 = String(reader.result).split(',')[1] ?? ''; setUpload({ filename: f.name, mimeType: f.type, contentBase64: b64 }); if (!title) setTitle(f.name.replace(/\.[^.]+$/, '')); };
    reader.readAsDataURL(f);
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault(); setError(''); setBusy(true);
    try {
      if (mode === 'write') {
        await api('/api/documents', { method: 'POST', body: JSON.stringify({ title, type: docType, content, projectId: projectId || undefined }) });
        flash('Document saved.');
      } else if (mode === 'import') {
        const payload = upload ? { title, projectId: projectId || undefined, ...upload } : { title, projectId: projectId || undefined, text: content };
        await api('/api/documents/ingest', { method: 'POST', body: JSON.stringify(payload) });
        flash('Document imported and indexed.');
      } else {
        await api('/api/documents/generate', { method: 'POST', body: JSON.stringify({ kind, title, projectId: projectId || undefined, sourceText: sourceText || undefined }) });
        flash('Document generated by AI and saved as a Draft.');
      }
      resetForm(); load();
    } catch (err) { setError((err as Error).message); } finally { setBusy(false); }
  }

  const filtered = docs.filter((d) => !q || d.title.toLowerCase().includes(q.toLowerCase()) || d.content.toLowerCase().includes(q.toLowerCase()));

  return (
    <div>
      <div className="topbar">
        <div><h1>Documentation</h1><p className="muted">Write, import or AI-generate specs, post-mortems, guides and schemas — all indexed for the agent.</p></div>
        <span className="badge">{docs.length} documents</span>
      </div>
      {error && <div className="error-banner">{error}</div>}
      {toast && <div className="notice section">{toast}</div>}

      <div className="grid main-sidebar section">
        <div className="card">
          <div className="av-row" style={{ marginBottom: 10 }}>
            <h3 style={{ flex: 1, margin: 0 }}>Documentation Centre</h3>
            <input placeholder="Search documents…" value={q} onChange={(e) => setQ(e.target.value)} style={{ maxWidth: 240 }} />
          </div>
          {loading ? <Spinner /> : filtered.length === 0 ? <Empty title={q ? 'No matches' : 'No documents yet'} hint={manage ? 'Generate or import one on the right.' : undefined} icon="file" /> : filtered.map((d) => (
            <div className="task" key={d.id} style={{ marginBottom: 12 }}>
              <b style={{ cursor: 'pointer' }} onClick={() => setOpenId(openId === d.id ? null : d.id)} title="Click to expand / collapse">{d.title}</b>
              <span className="chip" style={{ marginLeft: 6 }}>{d.type}</span>
              <small>{d.project?.name ?? 'General'} · {d.status} · updated {fmtDate(d.updatedAt)}</small>
              {openId === d.id
                ? <div className="section"><RichContent markdown={d.content} /></div>
                : <p className="small" style={{ whiteSpace: 'pre-wrap' }}>{d.content.slice(0, 320)}{d.content.length > 320 ? '…' : ''}</p>}
            </div>
          ))}
        </div>

        {manage && (
          <form className="card" onSubmit={submit}>
            <h3>Create a document</h3>
            <div className="seg-tabs">
              {(['generate', 'import', 'write'] as Mode[]).map((m) => (
                <button key={m} type="button" className={mode === m ? 'on' : ''} onClick={() => setMode(m)}>{m === 'generate' ? 'AI Generate' : m === 'import' ? 'Import' : 'Write'}</button>
              ))}
            </div>

            <div className="field"><label>Title</label><input value={title} onChange={(e) => setTitle(e.target.value)} required /></div>
            <div className="field"><label>Project (optional)</label>
              <select value={projectId} onChange={(e) => setProjectId(e.target.value)}>
                <option value="">General</option>
                {projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
              </select>
            </div>

            {mode === 'write' && (
              <>
                <div className="field"><label>Type</label>
                  <select value={docType} onChange={(e) => setDocType(e.target.value)}>
                    <option>Project Brief</option><option>Technical Documentation</option><option>User Guide</option><option>Admin Guide</option><option>Change Log</option><option>Release Notes</option>
                  </select>
                </div>
                <div className="field"><label>Content</label><textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder="Write the document…" /></div>
              </>
            )}

            {mode === 'import' && (
              <>
                <div className="field"><label>Upload a file (Markdown, text, code or PDF)</label><input ref={fileRef} type="file" accept=".md,.txt,.pdf,.json,.ts,.js,.py,.java,.cs,.go,.rb,.yml,.yaml,text/*,application/pdf" onChange={onFile} /></div>
                {upload && <p className="muted small">Ready to import: <b>{upload.filename}</b></p>}
                <div className="divider">or paste content</div>
                <div className="field"><label>Pasted content</label><textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder="Paste markdown / text / code…" /></div>
              </>
            )}

            {mode === 'generate' && (
              <>
                <div className="field"><label>Document kind</label>
                  <select value={kind} onChange={(e) => setKind(e.target.value)}>{GEN_KINDS.map((k) => <option key={k} value={k}>{k}</option>)}</select>
                </div>
                <div className="field"><label>Source material / context (optional)</label><textarea value={sourceText} onChange={(e) => setSourceText(e.target.value)} placeholder="Paste relevant notes, code or an imported doc's text. The AI also uses the live system state." /></div>
                <p className="muted small">The AI generates from your input plus the current projects/tasks snapshot, and saves the result as a Draft.</p>
              </>
            )}

            <button className="btn green full" disabled={busy || !title.trim()}>
              {busy ? (mode === 'generate' ? 'Generating…' : 'Saving…') : mode === 'generate' ? 'Generate with AI' : mode === 'import' ? 'Import document' : 'Save document'}
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
